# Generated by Django 5.0.2 on 2024-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('original_image', models.ImageField(blank=True, upload_to='images/original/')),
                ('augmented_image', models.ImageField(blank=True, upload_to='images/augmented/')),
            ],
        ),
        migrations.DeleteModel(
            name='input_image',
        ),
    ]
